### PR TITLE
#44 fixes paths

### LINKED ISSUE #44: GitHub pages after login and logout issue
**The loginListener function sends you to the incorrect place after login when deployed to GitHub pages.**

src/js/listeners/auth/login.js
 
```js
  location.href = `/?view=profile&name=${name}`;
```

Suggested change:

```js
  location.href = `./?view=profile&name=${name}`;
```

**The logoutListener function sends you to the incorrect place after login when deployed to GitHub pages.**

src/js/listeners/auth/logout.js
 
```js
  window.location.href = "/";
```

Suggested change:

```js
  window.location.href = "./";
```

### PR DESCRIPTION
**Pull request by Fermain**
Resolves #44

Paths are changed to `./` so that they will work despite the app being hosted in a directory.

### CODE REVIEW

File: src/js/listeners/auth/logout.js [hunk 1]
```diff
@@ -4,5 +4,5 @@ import { updateLoginVisibility } from "../../ui/auth.js";
 export function logoutListener() {
   auth.logout()
   updateLoginVisibility()
-  window.location.href = "/"
+  window.location.href = "./"
```
Comment (Fermain) [inline src/js/listeners/auth/logout.js:7]:
```suggestion
  location.href = "./"
```

**Review by jaaneh — APPROVED** [review]
